name: update-visualizer
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "output-diagram.svg"
          artifact_name: "my-diagram"
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: "my-diagram"
          path: "./downloads"
              

      
